interfuser:
  repo: "../InterFuser"
  agent_path: "impl/ads/agent/interfuser_agent.py"
  versions:
    - name: "v1"
      agent_config: "impl/ads/agent/interfuser_config_v1.py"
    - name: "v2"
      agent_config: "impl/ads/agent/interfuser_config_v2.py"

