debug: false

workspace:
  root: out
  log: logs
  result: results
  visualization: visualizations
  test_result: tests
  previous_solution: previous_solutions
  exp_result: exp_results

search:
  budget:
    max_sim: 500  # Set`null` to make it unlimited
    max_gen: 100  # Set`null` to make it unlimited
    max_time: 3600  # Set`null` to make it unlimited
  seeds: null  # Options: runtime, previous, null
  critical:
    mode: dpp  # Options: dpp, threshold
    k: null
    fitness: 20
    distance: 20
  constraint:
    enable: false
    threshold: 0.5
    penalty_base: 2.71828
    penalty_amplifier: 6.66
  multi_objective:
    enable: false  # Do NOT enable multi-objective and constraints at the same time
    algorithm: rnsga2  # Options: rnsga2, rnsga3
    ref_points:
      - [ 0.1, 0.9 ]
      - [ 0.2, 0.8 ]
  opt:
    diversity: true
    niching:
      strategy: clearing  # Options: clearing, sharing, null
      punishment: 1.0
      scaling: 1.0
      capacity: 1

scenario:
  pop_size: &pop 7
  archive_size: &arc 3
  dist_scaling: 1.0 # 0.4
  tournament: 3
  cxpb: 0.8
  mutpb: 0.2

perturbation:
  pop_size: *pop
  archive_size: *arc
  dist_scaling: 1.0
  tournament: 3
  cxpb: 0.8
  mutpb: 0.2
  overproduction: 10