debug: false

workspace:
  root: out
  log: logs
  test_result: tests
  checkpoint: checkpoints
  solution: solutions
  visualization: visualizations
  sim_result: results
  sim_save: results/eval

simulation:
  repo: "../InterFuser"
  parallel: true
  retry_times: 1
  display_agent: false
  scenario_duration: 20
  client_timeout: 10
  wait_for_world: 20
  frame_rate: 10
  high_graphics: true
  docker:
    enabled: true
    image: carla-0.9.10
    memory: 2g
    cpu: 1.5
    instances:
      - host: localhost
        port: 2000
        tm_port: 2500
        gpu_device: 0
      - host: localhost
        port: 2002
        tm_port: 2502
        gpu_device: 1

budget:
  max_sim: 1000
  max_time: 3600
  max_gen: 20
  convergence_threshold: 0.9

scenario:
  pop_size: 10
  archive_size: 3
  leaderboard_pb: 0.8
  init_pb:
    vehicle: 0.4
    walker: 0.5
    static: 0.1
  max_actors: 4
  init_selection_factor: 1
  dist_scaling: 0.4
  tournament: 3
  cxpb: 0.8
  eta: 10.0
  mutpb: 0.2
  mut_add: 0.6
  mut_del: 0.2

perturbation:
  pop_size: 10
  archive_size: 3
  dist_scaling: 1.0
  tournament: 3
  cxpb: 0.8
  mutpb: 0.2
  mut_add: 0.6
  mut_del: 0.2

violation:
  strategy: simulation  # Options: curve, simulation
  threshold:
    velocity: 1.0
    steer: 0.1
    max_ego_distance: 5 # Maximum distance in meters between ego-vehicle and closest object in simulation-based strategy
  dtw: true

opt:
  niching:
    strategy: clearing  # Options: none, sharing, clearing
    punishment: 1.0
    scaling: 1.0
    capacity: 2
  diversity: true

trajectory:
  - town: Town05
    start:
      x: -188.04
      y: 111.89
      z: 0.0
      yaw: -90.0
    direction:
      - left
      - forward

  - town: Town05
    start:
      x: -184.54
      y: 111.96
      z: 0.0
      yaw: -90.0
    direction:
      - right
      - forward


boundary:
  region:
    left:
      radius: [ 5.0, 17.0 ]
      angle: [ -70.0, -30.0 ]
    focus:
      radius: [ 5.0, 24.0 ]
      angle: [ -30.0, 30.0 ]
    right:
      radius: [ 5.0, 17.0 ]
      angle: [ 30.0, 70.0 ]
  vehicle:
    yaw: &yaw [ -180.0, 180.0 ]
    speed: [ -100.0, 80.0 ]
    model: [ 0, 22 ]
    base_model:
      car: [ 0, 17 ]
      truck: [ 18, 19 ]
      van: [20, 20]
      motorcycle: [ 21, 21 ]
      bicycle: [22, 22]
    autopilot: [ 1, 1 ]
  walker:
    yaw: *yaw
    speed: [ 0.0, 4.0 ]
    model: [ 0, 14 ]
  static:
    yaw: *yaw
    model: [ 0, 87 ]
  env:
    weather: [ 0, 14 ]

blueprint:
  vehicle:
    model:
      - "vehicle.audi.a2"
      - "vehicle.audi.etron"
      - "vehicle.audi.tt"
      - "vehicle.bmw.grandtourer"
      - "vehicle.chevrolet.impala"
      - "vehicle.citroen.c3"
      - "vehicle.dodge_charger.police"
      - "vehicle.bmw.isetta"
      - "vehicle.jeep.wrangler_rubicon"
      - "vehicle.lincoln.mkz2017"
      - "vehicle.mercedes-benz.coupe"
      - "vehicle.mini.cooperst"
      - "vehicle.mustang.mustang"
      - "vehicle.nissan.micra"
      - "vehicle.nissan.patrol"
      - "vehicle.seat.leon"
      - "vehicle.tesla.model3"
      - "vehicle.toyota.prius"
      - "vehicle.carlamotors.carlacola" # truck
      - "vehicle.tesla.cybertruck" # truck
      - "vehicle.volkswagen.t2" # van
      - "vehicle.kawasaki.ninja" # motorcycle
      - "vehicle.gazelle.omafiets" #bicycle
  walker:
    model:
      - "walker.pedestrian.0001"
      - "walker.pedestrian.0002"
      - "walker.pedestrian.0003"
      - "walker.pedestrian.0004"
      - "walker.pedestrian.0005"
      - "walker.pedestrian.0006"
      - "walker.pedestrian.0007"
      - "walker.pedestrian.0008"
      - "walker.pedestrian.0009"
      - "walker.pedestrian.0010"
      - "walker.pedestrian.0011"
      - "walker.pedestrian.0012"
      - "walker.pedestrian.0013"
      - "walker.pedestrian.0014"
      - "walker.pedestrian.0015"
  static:
    model:
      - "static.prop.advertisement"
      - "static.prop.atm"
      - "static.prop.barbeque"
      - "static.prop.barrel"
      - "static.prop.bench01"
      - "static.prop.bench02"
      - "static.prop.bench03"
      - "static.prop.bike helmet"
      - "static.prop.bin"
      - "static.prop.box01"
      - "static.prop.box02"
      - "static.prop.box03"
      - "static.prop.briefcase"
      - "static.prop.brokentile01"
      - "static.prop.brokentile02"
      - "static.prop.brokentile03"
      - "static.prop.brokentile04"
      - "static.prop.busstop"
      - "static.prop.chainbarrier"
      - "static.prop.chainbarrierend"
      - "static.prop.clothcontainer"
      - "static.prop.clothesline"
      - "static.prop.colacan"
      - "static.prop.constructioncone"
      - "static.prop.container"
      - "static.prop.creasedbox01"
      - "static.prop.creasedbox02"
      - "static.prop.creasedbox03"
      - "static.prop.dirtdebris01"
      - "static.prop.dirtdebris02"
      - "static.prop.dirtdebris03"
      - "static.prop.doghouse"
      - "static.prop.fountain"
      - "static.prop.garbage01"
      - "static.prop.garbage02"
      - "static.prop.garbage03"
      - "static.prop.garbage04"
      - "static.prop.garbage05"
      - "static.prop.garbage06"
      - "static.prop.gardenlamp"
      - "static.prop.glasscontainer"
      - "static.prop.gnome"
      - "static.prop.guitarcase"
      - "static.prop.ironplank"
      - "static.prop.kiosk_01"
      - "static.prop.mailbox"
      - "static.prop.maptable"
      - "static.prop.mobile"
      - "static.prop.motorhelmet"
      - "static.prop.pergola"
      - "static.prop.plantpot01"
      - "static.prop.plantpot02"
      - "static.prop.plantpot03"
      - "static.prop.plantpot04"
      - "static.prop.plantpot05"
      - "static.prop.plantpot06"
      - "static.prop.plantpot07"
      - "static.prop.plantpot08"
      - "static.prop.plasticbag"
      - "static.prop.plasticchair"
      - "static.prop.plastictable"
      - "static.prop.platformgarbage01"
      - "static.prop.purse"
      - "static.prop.shoppingbag"
      - "static.prop.shoppingcart"
      - "static.prop.shoppingtrolley"
      - "static.prop.slide"
      - "static.prop.streetbarrier"
      - "static.prop.streetfountain"
      - "static.prop.streetsign"
      - "static.prop.streetsign01"
      - "static.prop.streetsign04"
      - "static.prop.swing"
      - "static.prop.swingcouch"
      - "static.prop.table"
      - "static.prop.trafficcone01"
      - "static.prop.trafficcone02"
      - "static.prop.trafficwarning"
      - "static.prop.trampoline"
      - "static.prop.trashbag"
      - "static.prop.trashcan01"
      - "static.prop.trashcan02"
      - "static.prop.trashcan03"
      - "static.prop.trashcan04"
      - "static.prop.trashcan05"
      - "static.prop.travelcase"
      - "static.prop.vendingmachine"
      - "static.prop.wateringcan"
  scenario:
    weather:
      - "ClearNoon"
      - "ClearSunset"
      - "CloudyNoon"
      - "CloudySunset"
      - "Default"
      - "HardRainNoon"
      - "HardRainSunset"
      - "MidRainSunset"
      - "MidRainyNoon"
      - "SoftRainNoon"
      - "SoftRainSunset"
      - "WetCloudyNoon"
      - "WetCloudySunset"
      - "WetNoon"
      - "WetSunset"
